[package]
name = "Examples"
version = "0.0.0"

[addresses]
MyModule = "0x774b7430a3dc9c08fbe39838fbe5c1bbf145af13a19431520b3736f9c0889fc5"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-node-v1.2.0" }